# Generated by Django 5.0.1 on 2024-03-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trust_profile',
            name='balance_amt',
            field=models.FloatField(default=0),
        ),
    ]
