# Generated by Django 5.0.1 on 2024-04-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trust_profile_balance_amt'),
    ]

    operations = [
        migrations.CreateModel(
            name='amt_utilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('trust', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=500)),
                ('used_amt', models.FloatField()),
                ('proof', models.ImageField(upload_to='proof/')),
            ],
        ),
    ]
