# Generated by Django 5.0 on 2024-10-16 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_amt_utilization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trust_profile',
            old_name='contat_number',
            new_name='contact_number',
        ),
    ]
