# Generated by Django 5.1.6 on 2026-01-16 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_wallet',
        ),
    ]
