# Generated by Django 5.1.6 on 2026-01-16 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_user_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amt_utilization',
            name='proof',
        ),
        migrations.AddField(
            model_name='amt_utilization',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Medical', 'Medical'), ('Education', 'Education'), ('Shelter', 'Shelter'), ('Emergency', 'Emergency'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='amt_utilization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amt_utilization',
            name='donation_hash',
            field=models.CharField(default='LEGACY_DATA', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amt_utilization',
            name='proof_bill',
            field=models.FileField(blank=True, null=True, upload_to='proof/bills/'),
        ),
        migrations.AddField(
            model_name='amt_utilization',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='proof/images/'),
        ),
        migrations.AddField(
            model_name='amt_utilization',
            name='utilization_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
