# Generated by Django 5.1.6 on 2026-01-16 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_amt_utilization_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amt_utilization',
            name='donation_hash',
        ),
        migrations.AddField(
            model_name='amt_utilization',
            name='blockchain_tx_hash',
            field=models.CharField(default=django.utils.timezone.now, help_text='Ethereum transaction hash generated via MetaMask', max_length=66, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trust_profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trust_profile',
            name='eth_address',
            field=models.CharField(default=django.utils.timezone.now, help_text='Ethereum wallet address of the trust (MetaMask / Ganache)', max_length=42),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amt_utilization',
            name='trust',
            field=models.CharField(help_text='Trust / NGO name', max_length=100),
        ),
        migrations.AlterField(
            model_name='amt_utilization',
            name='user',
            field=models.CharField(help_text='Donor username (masked identity)', max_length=50),
        ),
        migrations.AlterField(
            model_name='trust_profile',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
