# Generated by Django 5.1.6 on 2026-01-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_amt_utilization_donation_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amt_utilization',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='trust_profile',
            name='eth_address',
            field=models.CharField(blank=True, help_text='Ethereum wallet address of the trust', max_length=42, null=True),
        ),
    ]
