# Generated by Django 5.1.6 on 2026-01-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_amt_utilization_blockchain_tx_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amt_utilization',
            name='proof_bill',
        ),
        migrations.RemoveField(
            model_name='amt_utilization',
            name='proof_image',
        ),
        migrations.AlterField(
            model_name='amt_utilization',
            name='category',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='amt_utilization',
            name='trust',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='amt_utilization',
            name='user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trust_profile',
            name='eth_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
