# Generated by Django 5.1.6 on 2026-01-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_amt_utilization_proof_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trust_profile',
            name='eth_address',
            field=models.CharField(blank=True, help_text='Ethereum wallet address of the trust (MetaMask / Ganache)', max_length=42, null=True),
        ),
    ]
