# Generated by Django 5.1.6 on 2026-01-20 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_trust_profile_eth_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amt_utilization',
            name='utilization_date',
        ),
        migrations.AlterField(
            model_name='amt_utilization',
            name='purpose',
            field=models.CharField(default='Donation', max_length=500),
        ),
        migrations.AlterField(
            model_name='amt_utilization',
            name='trust',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='amt_utilization',
            name='user',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='trust_profile',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='trust_profile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='trust_profile',
            name='eth_address',
            field=models.CharField(blank=True, help_text='Ethereum wallet address of the trust (starts with 0x)', max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='trust_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
