# Generated by Django 5.1.6 on 2026-01-20 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_amt_utilization_utilization_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amt_utilization',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='amt_utilization',
            name='trust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizations', to='app.trust_profile'),
        ),
        migrations.AlterField(
            model_name='amt_utilization',
            name='used_amt',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='amt_utilization',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trust_profile',
            name='balance_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trust_profile',
            name='eth_address',
            field=models.CharField(blank=True, help_text='Ethereum wallet address of the trust (starts with 0x)', max_length=42, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='amt_utilization',
            index=models.Index(fields=['created_at'], name='app_amt_uti_created_d60f80_idx'),
        ),
        migrations.AddIndex(
            model_name='amt_utilization',
            index=models.Index(fields=['category'], name='app_amt_uti_categor_4fc30e_idx'),
        ),
    ]
