# Generated by Django 5.1.6 on 2026-01-20 10:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_amt_utilization_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amt_utilization',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='amt_utilization',
            name='app_amt_uti_created_d60f80_idx',
        ),
        migrations.RemoveIndex(
            model_name='amt_utilization',
            name='app_amt_uti_categor_4fc30e_idx',
        ),
        migrations.AddField(
            model_name='amt_utilization',
            name='utilization_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amt_utilization',
            name='purpose',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='amt_utilization',
            name='trust',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='amt_utilization',
            name='used_amt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='amt_utilization',
            name='user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trust_profile',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trust_profile',
            name='balance_amt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trust_profile',
            name='contact_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trust_profile',
            name='eth_address',
            field=models.CharField(blank=True, help_text='Ethereum wallet address of the trust (MetaMask / Ganache)', max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='trust_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
