# Generated by Django 5.1.6 on 2026-01-22 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_amt_utilization_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trust_profile',
            name='balance_amt',
        ),
        migrations.AlterField(
            model_name='trust_profile',
            name='eth_address',
            field=models.CharField(default=django.utils.timezone.now, help_text='Ethereum wallet address of the trust (MetaMask)', max_length=42, unique=True),
            preserve_default=False,
        ),
    ]
