# Generated by Django 5.1.6 on 2026-01-22 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_trust_profile_balance_amt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Amount donated (verified from blockchain)')),
                ('tx_hash', models.CharField(help_text='Ethereum transaction hash (MetaMask / Ganache)', max_length=66, unique=True)),
                ('integrity_hash', models.CharField(help_text='Derived checksum for DB integrity verification', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(blank=True, help_text='Registered donor (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Utilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.FloatField(help_text='Amount utilized from the donation')),
                ('purpose', models.CharField(max_length=500)),
                ('category', models.CharField(default='Other', max_length=50)),
                ('proof', models.ImageField(blank=True, help_text='Bill / invoice / proof image', null=True, upload_to='utilization_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='amt_utilization',
        ),
        migrations.AlterField(
            model_name='trust_profile',
            name='eth_address',
            field=models.CharField(help_text='Ethereum public wallet address of the trust (MetaMask)', max_length=42, unique=True),
        ),
        migrations.AlterField(
            model_name='trust_profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='trust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='app.trust_profile'),
        ),
        migrations.AddField(
            model_name='utilization',
            name='donation',
            field=models.ForeignKey(help_text='Linked donation transaction', on_delete=django.db.models.deletion.CASCADE, related_name='utilizations', to='app.donation'),
        ),
        migrations.AddField(
            model_name='utilization',
            name='trust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trust_profile'),
        ),
    ]
