# Generated by Django 5.1.6 on 2026-01-23 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_donation_utilization_delete_amt_utilization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='utilization',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilization',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilization',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_utilizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilization',
            name='amount_used',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='utilization',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizations', to='app.donation'),
        ),
        migrations.AlterField(
            model_name='utilization',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='utilization_proofs/'),
        ),
    ]
